language: node_js

node_js:
  - 9

cache:
  directories:
  - node_modules

script:
  - npm run build

after_success:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  email: drdimsade@gmail.com
  name: sadinho
  local-dir: build
  on:
    branch: master
