import {MigrationInterface, QueryRunner} from "typeorm";

export class CreateStructureTexts1647875368105 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS categorias(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        nome_categoria VARCHAR(255) NOT NULL
      );
    `);

    await queryRunner.query(`
      CREATE INDEX idx_categorias_nome ON categorias (nome_categoria);
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS produtos(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        nome_produto VARCHAR(255) NOT NULL,
        categoria_id INT
      );
    `);

    await queryRunner.query(`
      CREATE INDEX idx_produtos_nome ON produtos (nome_produto);
    `);

    await queryRunner.query(`
      UPDATE produtos SET categoria_id = 1 WHERE categoria_id = null;
    `);


  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE IF EXISTS produtos;
    `);

    await queryRunner.query(`
      DROP TABLE IF EXISTS categorias;
    `);

  }
}
